#! /bin/bash

set -e

function install_glassfish_user {
    echo "Adding a new group for Glassfish administration..."
    sudo groupadd glassfishadm

    echo "Adding user 'glassfish'..."
    sudo adduser --home /home/atlas --ingroup glassfishadm --system --shell /bin/bash atlas

    echo "Adding 'glassfish' user to be a Glassfish adminstrator..."
    sudo usermod -a -G glassfishadm atlas

    return 0
}

function configure_java {
    #echo "Removing OpenJDK if installed..."
    #sudo apt-get remove openjdk-6-jre openjdk-6-jdk

    #maybe you have to execute this here first, else
    #add-apt-repository might fail
    #sudo apt-get install python-software-properties

    #add new repository that contains sun java (see https://wiki.ubuntu.com/LucidLynx/ReleaseNotes)
    #sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner"

    #update to know about new repository
    #sudo apt-get update

    #now install Sun JDK
    #sudo apt-get install sun-java6-jdk  sun-java6-jre

    #echo "Getting rid of several automatically installed packages that are not needed anymore..."
    #sudo apt-get autoremove

    #optional:
    #make sure environment points to a valid install if you are replacing...
    #sudo update-alternatives --config java

    #check JDK by looking in the /etc/alternatives/ directory
    #cd /etc/alternatives
    #ls -lrt java*

    #setting JAVA_HOME globally for all users (only for bash)
    #vim /etc/bash.bashrc
    #append the following line:
    #export JAVA_HOME=/usr/lib/jvm/java-6-sun
    echo "Setting JAVA_HOME globally for all users (only for bash)..."
    echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/bash.bashrc

    #setting JAVA_HOME for everyone (best place for setting env vars globally)
    #see https://help.ubuntu.com/community/EnvironmentVariables for details
    #vim /etc/environment
    #append the following lines:
    #JAVA_HOME=/usr/lib/jvm/java-6-sun
    #we will set this here because it might prevent problems later
    #AS_JAVA=/usr/lib/jvm/java-6-sun

    echo "Setting JAVA_HOME and AS_JAVA for everyone (best place for setting env vars globally)..."
    echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/environment
    echo "AS_JAVA=/usr/lib/jvm/java-6-sun" >> /etc/environment

    return 0
}

function install_glassfish {
    #if you dont't have "unzip" installed run this here first
    #sudo apt-get install unzip

    #now switch user to the atlas user we created (see step 1)
    #sudo su atlas

    #change to home dir of atlas
    cd /home/atlas/

    #create new directory if not already available
    sudo -u atlas mkdir downloads

    #go to the directory we created
    cd /home/atlas/downloads/

    echo "Downloading Glassfish and installing..."
    sudo -u atlas wget http://download.java.net/glassfish/3.1/release/glassfish-3.1.zip
    sudo -u atlas unzip glassfish-3.1.zip

    #move the relevant content to home directory
    sudo -u atlas mv /home/atlas/downloads/glassfish3/* /home/atlas/
    #if something has not been moved, then move it manually, i.e.:
    sudo -u atlas mv /home/atlas/downloads/glassfish3/.org.opensolaris,pkg /home/atlas/.org.opensolaris,pkg

    #exit from atlas user
    #exit

    #change group of atlas home directory to glassfishadm
    sudo chgrp -R glassfishadm /home/atlas

    #just to make sure: change owner of atlas home directory to atlas
    sudo chown -R atlas /home/atlas

    #make sure the relevant files are executable/modifyable/readable for owner and group
    sudo chmod -R ug+rwx /home/atlas/bin/
    sudo chmod -R ug+rwx /home/atlas/glassfish/bin/

    #others are not allowed to execute/modify/read them
    sudo chmod -R o-rwx /home/atlas/bin/
    sudo chmod -R o-rwx /home/atlas/glassfish/bin/

    return 0
}

function configure_mysql {
    echo "Adding mysql database 'openstack_atlas' and mysql user 'atlas' with password 'password' (please change later)..."
    MYSQL=`which mysql`
    DATABASE="openstack_atlas"
    USER="atlas"
    PASSWORD="password"
     
    Q1="CREATE DATABASE IF NOT EXISTS $DATABASE;"
    Q2="GRANT ALL ON *.* TO '$USER'@'localhost' IDENTIFIED BY '$PASSWORD';"
    Q3="FLUSH PRIVILEGES;"
    SQL="${Q1}${Q2}${Q3}"

    echo "Please enter the root password for MySQL..."
    $MYSQL -uroot -p -e "$SQL"

    return 0
}

function install_and_start_activemq {
    #go to the directory we created
    cd /home/atlas/downloads/

    echo "Downloading ActiveMQ and installing..."
    sudo -u atlas wget http://apache.mirrors.tds.net//activemq/apache-activemq/5.5.1/apache-activemq-5.5.1-bin.tar.gz
    sudo -u atlas tar -xzvf apache-activemq-5.5.1-bin.tar.gz

    #move the relevant content to home directory
    sudo -u atlas mv /home/atlas/downloads/apache-activemq-5.5.1 /home/atlas/

    #go to the bin directory
    cd /home/atlas/apache-activemq-5.5.1/bin
    echo "Starting up ActiveMQ..."
    sudo -u atlas java -jar /home/atlas/apache-activemq-5.5.1/bin/run.jar start &
    echo "ActiveMQ successfully started."
}

function deploy_app {
    echo "Starting up proper ownership on atlas files..."
    chown -R atlas:glassfishadm /opt/openstack/atlas/
    chown -R atlas:glassfishadm /etc/openstack/atlas/

    echo "Starting up Glassfish..."
    sudo -u atlas /home/atlas/glassfish/bin/asadmin start-domain domain1
    echo "Glassfish successfully started."

    echo "Deploying Atlas WAR..."
    WAR_FILE=`ls /opt/openstack/atlas/api/*.war`
    sudo -u atlas /home/atlas/glassfish/bin/asadmin deploy --contextroot "/atlas" ${WAR_FILE}
    echo "WAR successfully deployed."

    return 0
}

function seed_database {
    echo "Seeding database with dummy data (cluster, hosts, vips, etc.)..."
    mysql -u atlas --password=password -D openstack_atlas < /opt/openstack/atlas/db/core-seed.sql
    echo "Database successfully seeded."
}

case "$1" in
    configure|triggered)
        echo "postinst called with arguments: '$1', '$2'"
        install_glassfish_user
        configure_java
        install_glassfish
        configure_mysql
        install_and_start_activemq
        deploy_app
        seed_database

        echo "Installation completed successfully. Atlas API available at http://localhost:8080/atlas"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        echo "postinst called with argument: '$1'"
    ;;

    *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 0
    ;;
esac

#DEBHELPER#

exit 0