#!/bin/bash
set -e

echo "Removing 'atlas' user..."
sudo deluser atlas

echo "Removing 'glassfishadm' group..."
sudo delgroup glassfishadm

echo "Removing old files..."
sudo rm -rf /home/atlas

#DEBHELPER#

exit 0