#!/bin/bash
set -e

#TODO: Drop database
#TODO: Remove JAVA_HOME variables from /etc/environment and /etc/bash.bashrc

echo "Removing 'atlas' user..."
sudo deluser atlas

echo "Removing 'glassfishadm' group..."
sudo delgroup glassfishadm

echo "Removing old files..."
sudo rm -rf /home/atlas

#DEBHELPER#

exit 0